### ISSUE TITLE
Which changes to do in publish.launch for eye on base

### ISSUE THREAD

**Issue by Akumar201** [IFL-CAMP/easy_handeye#114] opened 2022-10-14 21:41 UTC
Hello, 
I am using eye on base calibration, I would like to know how can I use my calibrated data to publish using publish.launch https://github.com/IFL-CAMP/easy_handeye/blob/master/easy_handeye/launch/publish.launch as almost every argument is related to eye on hand . How should I edit it to make it for eye on base 

```
<?xml version="1.0"?>
<launch>
    <arg name="eye_on_hand" doc="eye-on-hand instead of eye-on-base" />
    <arg name="namespace_prefix" default="easy_handeye" />
    <arg if="$(arg eye_on_hand)" name="namespace" value="$(arg namespace_prefix)_eye_on_hand" />
    <arg unless="$(arg eye_on_hand)" name="namespace" value="$(arg namespace_prefix)_eye_on_base" />

    <!--it is possible to override the link names saved in the yaml file in case of name clashes, for example-->
    <arg if="$(arg eye_on_hand)" name="robot_effector_frame" default="" />
    <arg unless="$(arg eye_on_hand)" name="robot_base_frame" default="" />
    <arg name="tracking_base_frame" default="" />
    
    <arg name="inverse" default="false" />
    <arg name="calibration_file" default="" />
    
    <!--publish hand-eye calibration-->
    <group ns="$(arg namespace)">
        <param name="eye_on_hand" value="$(arg eye_on_hand)" />
        <param unless="$(arg eye_on_hand)" name="robot_base_frame" value="$(arg robot_base_frame)" />
        <param if="$(arg eye_on_hand)" name="robot_effector_frame" value="$(arg robot_effector_frame)" />
        <param name="tracking_base_frame" value="$(arg tracking_base_frame)" />
        <param name="inverse" value="$(arg inverse)" />
        <param name="calibration_file" value="$(arg calibration_file)" />
        <node name="$(anon handeye_publisher)" pkg="easy_handeye" type="publish.py" output="screen"/>
    </group>
</launch>
```

**Comment by marcoesposito1988** [comment] 2022-10-16 21:20
Duplicate of #113

**Closed by marcoesposito1988** 2022-10-16 21:20 UTC
